projName:=Extra_battery_package01
msp430DebugNameS:=Debug__GNU Debug__TI Debug Debug__TIT Debug__TIH
projFullName:=Extra battery package01

testOBJs:=tt5 tt1 tt2 tt3 tt4
testOBJs:=tt1 tt2
testOBJs:=tt1


##### Project custom define : begin
b1:
	gcc
t: ttt
##### Project custom define : end

t1 : 
	make k51 
	make burn1


g:
	$(foreach aa1,src09/ h09/ Extra_battery_package01/, cd $(aa1) || ( echo dir _ $(aa1) _ do NOT exist. )$(EOL))
	( cd src09/ && ln -s ../Extra_battery_package01/*.c ./ ) || ( echo; echo nothing link ; echo )
	( cd h09/   && ln -s ../Extra_battery_package01/*.h ./ ) || ( echo; echo nothing link ; echo )

define helpText2
endef
export helpText2

